version: "3.8"
networks:
  appnet: { driver: bridge }
services:
  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [ app ]
    networks: [ appnet ]
  app:
    build:
      context: "docker/app/"
    ports:
      - 8080:80 
      - 8081:81
      - 5173:5173 # viteで使用するポートをフォワード
    working_dir: /var/www
    volumes:
      - "./www/:/var/www"
      - "./docker/app/apache2/apache2.conf:/etc/apache2/apache2.conf"
      - "./docker/app/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      - "./docker/msmtp/msmtprc:/etc/msmtprc"
    depends_on:
      - mysql
      - mailhog
    expose:
      - "8000"
    command: php -S 0.0.0.0:8000 -t public
    networks: [ appnet ]


  mysql:
    build:
      context: "docker/mysql/"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test_db_name
      - MYSQL_HOST=mysql
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_pass
      - MYSQL_ROOT_PASSWORD=test_root_pass
      - TZ=Asia/Tokyo
    volumes:
      - "./docker/mysql/storage/:/var/lib/mysql"
      - "./docker/mysql/initdb/:/docker-entrypoint-initdb.d"
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8082:80"   # ← 81を8082に変更
    environment:
      - PMA_HOST=mysql
      - PMA_USER=test_user
      - PMA_PASSWORD=test_pass
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"

#  livekit:
#    image: livekit/livekit-server:v1.6.2
#    container_name: livekit
#    command: [ "--dev","--bind","0.0.0.0" ]   # ← "::" をいったんやめる
#    ports:
#      - "7882:7880"         # ホスト:コンテナ
#      - "7881:7881/udp"
#    restart: unless-stopped
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    command: ["--config","/config.yaml","--bind","0.0.0.0","--dev","--bind 0.0.0"]
    ports:
      - "7880:7880"        # HTTP/WS
      - "7881:7881"        # WebRTC/TCP
      - "7882:7882/udp"    # WebRTC/UDP
    volumes:
      - ./livekit/config.yaml:/config.yaml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:7880/"]
      interval: 10s
      timeout: 3s
      retries: 5


volumes:
  storage:
