log_level: info
port: 7880
bind_addresses:
  - "0.0.0.0"
  - "::"

rtc:
  tcp_port: 7881
  udp_port: 7882
  allow_tcp_fallback: true
  force_tcp: true
  use_external_ip: false
#  node_ip: host.docker.internal